---
- name: Delete db-subnet-group stack
  cloudformation:
    stack_name: "{{prefix}}db-subnet-group"
    state: "absent"
    region: "{{ region }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ session_token }}"

- name: Call Git role
  include_role:
    name: git-delete
  vars:
    github_enterprise_org: gp-ops-non-prod
    github_enterprise_repo: cft-infra-templates
    message: "Ansible deleting db-subnet-group"
    folder_name: "db-subnet-group"