---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create Secrets.

Resources:

  ArtifactoryKeyPair:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: "Username and API Encrypted Password for the Jfrog Artifactory"
      Name: automation/ArtifactorySecrets
      SecretString: '{"username": "502813500","password":"AP6NwxN34RDZiefx4gwe2cx1Ktc"}'
      Tags: 
        - Key: CoreComponent
          Value: True
        - Key: UAI
          Value: uai3026350
        - Key: Team
          Value: EA