plugin: aws_ec2
regions:
 - {{ aws_region }}
iam_role_arn: arn:aws:iam::{{ aws_account_id }}:role/app/uai3047316/gp-ansible-execution
filters:
 tag:ansiblehost: 
   - Windows
   - Linux/UNIX
 instance-state-name : running  
keyed_groups:
 - key: tags.ansiblehost.split("/")[0]
   prefix: instance
compose:
  ansible_host: private_ip_address