AWSTemplateFormatVersion: "2010-09-09"
Description: evm team readonly jump aacess fed role

Parameters:

  RoleName:
    Type: String
    Description: Name of the  Role... e.g. 'cldSAAdmin'
    Default: 'evm'
  AdminAccountId:
    Type: String
    MaxLength: 12
    MinLength: 12
    Default: "325381443140"
    Description: 12 digit AWS Account Id of the identity/federation account containing the users to which you're granting access. This is a trusted account.
  MultiFactorAuthRequired:
    Default: "False"
    Type: String
    AllowedValues:
      - "True"
      - "False"

Conditions:
  AdminSetup: !Equals [!Ref AWS::AccountId, '325381443140']
  SwitchSetup: !Not [!Equals [!Ref AWS::AccountId, '325381443140']]

Resources:

  EVMReadOnlyFedJumprole:
    Type: AWS::IAM::Role
    Condition: AdminSetup
    Properties:
      RoleName: !Sub bu-pw-${RoleName}-readonly
      Path: '/gp/'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - # Allow the role to be assumed from SAML Auth.
            Effect: Allow
            Principal:
              Federated: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:saml-provider/ge-saml-for-aws-mfa
            Action: 'sts:AssumeRoleWithSAML'
            Condition:
              StringEquals:
                'SAML:aud': 'https://signin.aws.amazon.com/saml'
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/GP-Read-Only-Policy"
      Policies:
        - PolicyName: AssumeRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:

              - Sid: AssumeRole
                Action:
                  - sts:AssumeRole
                Resource:
                  - !Sub "arn:aws:iam::*:role/gp/bu-pw-${RoleName}-readonly"
                Effect: Allow

  EVMReadOnlyfedrole:
    Type: AWS::IAM::Role
    Condition: SwitchSetup
    Properties:
      RoleName: !Sub bu-pw-${RoleName}-readonly
      Path: '/gp/'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - # Allow the role to be assumed from Admin account.
            Effect: Allow 
            Principal:
              "AWS": !Sub "arn:${AWS::Partition}:iam::${AdminAccountId}:role/hq/bu-pw-${RoleName}-readonly"
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": !Ref MultiFactorAuthRequired
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/GP-Read-Only-Policy"
