---
  AWSTemplateFormatVersion: '2010-09-09'
  Description: Wiz AWS standard deployment

  Outputs:
    ExternalID:
      Description: Your External ID
      Value:
        Ref: ExternalId
    RoleARNID:
      Description: Your Role ARN ID
      Value:
        Fn::GetAtt:
        - Role
        - Arn

  Parameters:
    ExternalId:
      AllowedPattern: "\\S{8}-\\S{4}-\\S{4}-\\S{4}-\\S{12}"
      Description: Enter External ID, this is a nonce that will be used by our service
        to assume the role
      Default: 4043d4bc-8492-42a5-84e6-53fff828af41
      Type: String
    WizRoleName:
      Default: WizAccess-Role
      Description: Enter the role name that will be installed on your account, the default
        is WizAccess-Role
      Type: String
    UAI:
      Default: uai3047631
      Type: String

  Resources:
    Role:
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId:
                  Ref: ExternalId
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::197171649850:root
          Version: '2012-10-17'
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        RoleName: !Ref WizRoleName
        Path: !Sub /inf/${UAI}/
      Type: AWS::IAM::Role
    WizFullPolicy:
      Properties:
        PolicyDocument:
          Statement:
          - Action:
            - acm:GetCertificate
            - apigateway:GET
            - backup:DescribeGlobalSettings
            - backup:GetBackupVaultAccessPolicy
            - backup:GetBackupVaultNotifications
            - backup:ListBackupVaults
            - backup:ListTags
            - cloudtrail:GetInsightSelectors
            - cloudtrail:ListTrails
            - codebuild:BatchGetProjects
            - codebuild:GetResourcePolicy
            - codebuild:ListProjects
            - cognito-identity:DescribeIdentityPool
            - connect:ListInstances
            - connect:ListInstanceAttributes
            - connect:ListInstanceStorageConfigs
            - connect:ListSecurityKeys
            - connect:ListLexBots
            - connect:ListLambdaFunctions
            - connect:ListApprovedOrigins
            - connect:ListIntegrationAssociations
            - dynamodb:DescribeExport
            - dynamodb:DescribeKinesisStreamingDestination
            - dynamodb:ListExports
            - ec2:GetEbsEncryptionByDefault
            - ec2:SearchTransitGatewayRoutes
            - ecr:BatchGetImage
            - ecr:GetAuthorizationToken
            - ecr:GetDownloadUrlForLayer
            - ecr:GetRegistryPolicy
            - ecr-public:ListTagsForResource
            - eks:ListTagsForResource
            - elasticfilesystem:DescribeAccessPoints
            - elasticfilesystem:DescribeFileSystemPolicy
            - elasticmapreduce:GetAutoTerminationPolicy
            - elasticmapreduce:GetManagedScalingPolicy
            - glacier:GetDataRetrievalPolicy
            - glacier:GetVaultLock
            - glue:GetConnection
            - glue:GetSecurityConfiguration
            - glue:GetTags
            - health:DescribeAffectedAccountsForOrganization
            - health:DescribeAffectedEntities
            - health:DescribeAffectedEntitiesForOrganization
            - health:DescribeEntityAggregates
            - health:DescribeEventAggregates
            - health:DescribeEventDetails
            - health:DescribeEventDetailsForOrganization
            - health:DescribeEventTypes
            - health:DescribeEvents
            - health:DescribeEventsForOrganization
            - health:DescribeHealthServiceStatusForOrganization
            - kafka:ListClusters
            - kendra:DescribeDataSource
            - kendra:DescribeIndex
            - kendra:ListDataSources
            - kendra:ListIndices
            - kendra:ListTagsForResource
            - kinesisanalytics:ListApplications
            - kinesisanalytics:DescribeApplication
            - kinesisanalytics:ListTagsForResource
            - kinesisvideo:ListStreams
            - kinesisvideo:ListTagsForStream
            - kinesisvideo:GetDataEndpoint
            - kms:GetKeyRotationStatus
            - kms:ListResourceTags
            - lambda:GetFunction
            - lambda:GetLayerVersion
            - profile:GetDomain
            - profile:ListDomains
            - profile:ListIntegrations
            - s3:GetBucketNotification
            - s3:GetMultiRegionAccessPointPolicy
            - s3:ListMultiRegionAccessPoints
            - ses:DescribeActiveReceiptRuleSet
            - ses:GetAccount
            - ses:GetConfigurationSet
            - ses:GetConfigurationSetEventDestinations
            - ses:GetDedicatedIps
            - ses:GetEmailIdentity
            - ses:ListConfigurationSets
            - ses:ListDedicatedIpPools
            - ses:ListReceiptFilters
            - voiceid:DescribeDomain
            - wafv2:GetLoggingConfiguration
            - wafv2:GetWebACLForResource
            - wisdom:GetAssistant
            Effect: Allow
            Resource: "*"
          - Action:
            - ec2:CopySnapshot
            - ec2:CreateSnapshot
            - kms:CreateKey
            Effect: Allow
            Resource: "*"
          - Action:
            - ec2:CreateTags
            Effect: Allow
            Resource: arn:aws:ec2:*::snapshot/*
          - Action: kms:CreateAlias
            Effect: Allow
            Resource:
            - arn:aws:kms:*:*:alias/wizKey
            - arn:aws:kms:*:*:key/*
          - Action:
            - kms:CreateGrant
            - kms:ReEncryptFrom
            Condition:
              StringLike:
                kms:ViaService: ec2.*.amazonaws.com
            Effect: Allow
            Resource: "*"
          - Action:
            - kms:GetKeyPolicy
            - kms:PutKeyPolicy
            Condition:
              StringEquals:
                aws:ResourceTag/wiz: auto-gen-cmk
            Effect: Allow
            Resource: "*"
          - Action:
            - ec2:DeleteSnapshot
            - ec2:ModifySnapshotAttribute
            Condition:
              StringEquals:
                ec2:ResourceTag/wiz: auto-gen-snapshot
            Effect: Allow
            Resource: "*"
          - Action:
            - s3:GetObject
            - s3:GetBucketLocation
            - s3:GetObjectTagging
            - s3:ListBucket
            Effect: Allow
            Resource:
            - arn:aws:s3:::*terraform*
            - arn:aws:s3:::*tfstate*
            - arn:aws:s3:::*tf?state*
            - arn:aws:s3:::*cloudtrail*
            - arn:aws:s3:::elasticbeanstalk-*
            Sid: WizAccessS3
          Version: '2012-10-17'
        PolicyName: WizFullPolicy
        Roles:
        - Ref: Role
      Type: AWS::IAM::Policy
  