---
- name: Include vars file
  include_vars: main.yml

- name: Create a new directory <account-name>-<account-id>
  file:
    state: directory
    path: "{{source_directory}}/{{ aws_account_name }}-{{ aws_account_id }}"

- name: Copy 02-iam-common-policies.yml
  template:
    src: "02-iam-common-policies.yml"
    dest: "{{source_directory}}/{{ aws_account_name }}-{{ aws_account_id }}"

- name: Copy 04-iam-gr.yml
  template:
    src: "04-iam-gr.yml"
    dest: "{{source_directory}}/{{ aws_account_name }}-{{ aws_account_id }}"

- name: Copy 05-iam-common-roles.yml
  template:
    src: "05-iam-common-roles.yml"
    dest: "{{source_directory}}/{{ aws_account_name }}-{{ aws_account_id }}"

- name: Copy 06-iam-fed-roles.yml
  template:
    src: "06-iam-fed-roles.yml"
    dest: "{{source_directory}}/{{ aws_account_name }}-{{ aws_account_id }}"

- name: Copy 08-iam-ansible.yml
  template:
    src: "08-iam-ansible.yml"
    dest: "{{source_directory}}/{{ aws_account_name }}-{{ aws_account_id }}"

- debug: var=ansible_date_time

- name: Copy Ansible Metadata file
  template:
    src: "{{role_path}}/files/ansible_metadata.txt"
    dest: "{{source_directory}}/ansible_metadata.txt"
  vars:
    current_date_jinja: "{{ ansible_date_time.date }} {{ansible_date_time.time}} UTC"

- name: Call Git role
  include_role:
    name: git-push
  vars:
    github_enterprise_org: gp-ops
    github_enterprise_repo: gr-accounts-setup
    message: "Ansible rendered stackset files"

# Pause for 10 minutes to build app cache.
- pause:
    minutes: 10
