plugin: aws_ec2
regions:
 - us-east-1
iam_role_arn: arn:aws:iam::987201782067:role/app/uai3047316/gp-ansible-execution
filters:
 tag:ansiblehost: 
   - Windows
   - Linux/UNIX
 instance-state-name : running  
keyed_groups:
 - key: tags.ansiblehost.split("/")[0]
   prefix: instance
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address
