---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'cldSAAdmin Federated or switch role to EA Team.
              Template ref: https://github.build.ge.com/gp-ops/global-stack-sets/blob/master/iam-cldsa-admin-setup/templates/iam-sa-role-setup.yml'

Parameters:

  RoleName:
    Type: String
    Description: Name of the  Role... e.g. 'cldSAAdmin'
    Default: 'cldSAAdmin'
  RolePath:
    Type: String
    Description: Path for the role
    Default: 'hq'
  AdminAccountId:
    Type: String
    MaxLength: 12
    MinLength: 12
    Default: "325381443140"
    Description: 12 digit AWS Account Id of the identity/federation account containing the users to which you're granting access. This is a trusted account.
  MultiFactorAuthRequired:
    Default: "False"
    Type: String
    AllowedValues:
      - "True"
      - "False"

Conditions:
  AdminSetup: !Equals [!Ref AWS::AccountId, '325381443140']
  SwitchSetup: !Not [!Equals [!Ref AWS::AccountId, '325381443140']]

Resources:  
  
  SAAdminRole:
    Type: AWS::IAM::Role
    Condition: AdminSetup
    Properties:
      RoleName: !Sub bu-pw-${RoleName}-fed
      Path: !Sub /${RolePath}/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - # Allow the role to be assumed from SAML Auth.
            Effect: Allow
            Principal:
              Federated: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:saml-provider/ge-saml-for-aws-mfa
            Action: 'sts:AssumeRoleWithSAML'
            Condition:
              StringEquals:
                'SAML:aud': 'https://signin.aws.amazon.com/saml'
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/GP-Read-Only-Policy"
        - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/common-fed-role"  
        - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/ssm-session-deny"
        # - "arn:aws:iam::aws:policy/IAMFullAccess"  # IamFullAceess Managed Policy
        - "arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess"  # AWS OrganizationReadonly Access
      Policies:
        - PolicyName: AssumeRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:

              - Sid: AssumeRole
                Action:
                  - sts:AssumeRole
                Resource:
                  - "arn:aws:iam::*:role/hq/bu-pw-cldSAAdmin-fed"
                Effect: Allow
  CldSAAdminRole:
    Type: AWS::IAM::Role
    Condition: SwitchSetup
    Properties:
      RoleName: !Sub bu-pw-${RoleName}-fed
      Path: !Sub /${RolePath}/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - # Allow the role to be assumed from Admin account.
            Effect: Allow 
            Principal:
              "AWS": !Sub "arn:${AWS::Partition}:iam::${AdminAccountId}:role/hq/bu-pw-cldSAAdmin-fed"
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": !Ref MultiFactorAuthRequired
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/GP-Read-Only-Policy"
        - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/common-fed-role"  
        - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/ssm-session-deny"
        # - "arn:aws:iam::aws:policy/IAMFullAccess"  # IamFullAceess Managed Policy
        - "arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess"  # AWS OrganizationReadonly Access

  SaadminDenyPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub "${RoleName}-deny-access"
      Roles:
        'Fn::If':
        - AdminSetup
        - 
          - !Ref SAAdminRole
        - 
          - !Ref CldSAAdminRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyEc2Actions
            Action:
              - ec2:AssociateRouteTable
              - ec2:AssociateSubnetCidrBlock
              - ec2:AssociateTransitGatewayMulticastDomain
              - ec2:AssociateTransitGatewayRouteTable
              - ec2:AssociateVpcCidrBlock
              - ec2:AttachInternetGateway
              - ec2:CreateDefaultSubnet
              - ec2:CreateDefaultVpc
              - ec2:CreateLocalGatewayRoute
              - ec2:CreateLocalGatewayRouteTableVpcAssociation
              - ec2:CreateNatGateway
              - ec2:CreateNetworkAcl
              - ec2:CreateNetworkAclEntry
              - ec2:CreateRoute
              - ec2:CreateRouteTable
              - ec2:CreateSubnet
              - ec2:CreateTransitGateway*
              - ec2:CreateVpc
              - ec2:CreateVpcPeeringConnection
              - ec2:CreateVpn*
              - ec2:DeleteCarrierGateway
              - ec2:DeleteClientVpnEndpoint
              - ec2:DeleteClientVpnRoute
              - ec2:DeleteCustomerGateway
              - ec2:DeleteDhcpOptions
              - ec2:DeleteEgressOnlyInternetGateway
              - ec2:DeleteFlowLogs
              - ec2:DeleteKeyPair
              - ec2:DeleteInternetGateway
              - ec2:DeleteLocalGatewayRoute
              - ec2:DeleteLocalGatewayRouteTableVpcAssociation
              - ec2:DeleteManagedPrefixList
              - ec2:DeleteNatGateway
              - ec2:DeleteNetworkAcl
              - ec2:DeleteNetworkAclEntry
              - ec2:DeleteRoute
              - ec2:DeleteRouteTable
              - ec2:DeleteSubnet
              - ec2:DeleteTransitGateway*
              - ec2:DeleteVpc*
              - ec2:DeleteVpn*
              - ec2:DeprovisionByoipCidr
              - ec2:DetachInternetGateway
              - ec2:DetachVpnGateway
              - ec2:DisableTransitGatewayRouteTablePropagation
              - ec2:DisableVpcClassicLinkDnsSupport
              - ec2:DisableVpcClassicLink
              - ec2:DisassociateClientVpnTargetNetwork
              - ec2:DisassociateRouteTable
              - ec2:DisassociateSubnetCidrBlock
              - ec2:DisassociateTransitGateway*
              - ec2:DisassociateVpcCidrBlock
              - ec2:EnableTransitGatewayRouteTablePropagation
              - ec2:EnableVgwRoutePropagation
              - ec2:EnableVpcClassicLink
              - ec2:EnableVpcClassicLinkDnsSupport
              - ec2:ModifyClientVpnEndpoint
              - ec2:ModifySubnetAttribute
              - ec2:ModifyTransitGateway*
              - ec2:ModifyVpcAttribute
              - ec2:ModifyVpc*
              - ec2:ModifyVpn*
              - ec2:ProvisionByoipCidr
              - ec2:PurchaseHostReservation
              - ec2:ReplaceNetworkAclAssociation
              - ec2:ReplaceNetworkAclEntry
              - ec2:ReplaceRoute
              - ec2:ReplaceRouteTableAssociation
              - ec2:ReplaceTransitGatewayRoute
              - ec2:RevokeClientVpnIngress
              - ec2:TerminateClientVpnConnections
            Resource: '*'
            Effect: Deny

  SAAdminPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub "${RoleName}-access"
      Roles:
        'Fn::If':
        - AdminSetup
        - 
          - !Ref SAAdminRole
        - 
          - !Ref CldSAAdminRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:

          - Sid: PassRole
            Action:
              - iam:PassRole
            Resource:
              - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/app/*"
              - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/lam/*"
              - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*/bu-pw-*-app"
              - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/inf/*"
              - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/AWSDataLifecycleManagerDefaultRole"
              - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/REM-*"
            Effect: Allow

          - Sid: IAMControlsLimited
            Effect: Allow
            Action:
              - iam:Delete*
              - iam:List*
              - iam:Get*
              - iam:UpdateServerCertificate
              - iam:UpdateSigningCertificate
              - iam:UploadServerCertificate
              - iam:UploadSigningCertificate
              - iam:CreateServiceLinkedRole
              - iam:UpdateAssumeRolePolicy
            Resource:
              - "*"

          - Sid: CognitoFullAccess
            Effect: Allow
            Action:
              - cognito-identity:*
              - cognito-idp:*
              - cognito-sync:*
            Resource:
              - "*"
              
          - Sid: EnableAllControls
            Action:
              - a4b:*
              - acm:*
              - apigateway:*
              - application-autoscaling:*
              - appstream:*
              - kinesisvideo:*
              - athena:*
              - autoscaling:*
              - aws-marketplace:*
              - cloud9:*
              - codedeploy:*
              - codepipeline:*
              - codestar:*
              - codestar-connections:*
              - compute-optimizer:*
              - codebuild:*
              - codecommit:*
              - config:*
              - cloudformation:*
              - cloudtrail:*
              - cloudfront:*
              - cloudsearch:*
              - cloudwatch:*
              - cloudshell:*
              - datapipeline:*
              - dlm:*
              - dms:*
              - dynamodb:*
              - ec2:*
              - ec2-reports:*
              - ecs:*
              - ecr:*
              - elasticfilesystem:*
              - elasticache:*
              - elasticbeanstalk:*
              - elasticloadbalancing:*
              - elasticmapreduce:*
              - es:*
              - events:*
              - schemas:*
              - execute-api:*
              - glacier:*
              - glue:*
              - greengrass:*
              - inspector:*
              - kms:*
              - lambda:*
              - logs:*
              - machinelearning:*
              - opsworks:*
              - opsworks-cm:*
              - proton:*
              - quicksight:*
              - rds:*
              - redshift:*
              - resource-groups:*
              - sdb:*
              - s3:*
              - ses:*
              - snowball:*
              - sns:*
              - sqs:*
              - ssm:*
              - sts:DecodeAuthorizationMessage
              - support:*
              - swf:*
              - tag:*
              - trustedadvisor:*
              - waf:*
              - wafv2:*
              - waf-regional:*
              - xray:*
              - health:*
              - route53:*
              - route53domains:*
              - route53resolver:*
              - states:*
              - servicecatalog:*
              - sagemaker:*
              - serverlessrepo:*
              - secretsmanager:*
              - access-analyzer:*
              - servicequotas:*
              - appconfig:*
              - backup:*
            Resource: "*"
            Effect: Allow

Outputs:

  AdminSAFederatedRoleName:
    Condition: AdminSetup
    Value: !Ref SAAdminRole
  AdminSAFederatedRoleArn:
    Condition: AdminSetup
    Value: !GetAtt SAAdminRole.Arn

  SwitchSAFederatedRoleName:
    Condition: SwitchSetup
    Value: !Ref CldSAAdminRole
  SwitchSAFederatedRoleArn:
    Condition: SwitchSetup
    Value: !GetAtt CldSAAdminRole.Arn
