plugin: aws_ec2
regions:
 - us-east-1
iam_role_arn: arn:aws:iam::665129569626:role/app/uai3047316/gp-ansible-execution
filters:
 tag:bastionhost: 
   - "true"
 instance-state-name : running  
compose:
  ansible_host: private_ip_address
