---
account: '{{ aws_account_id }}'
region: "{{ aws_region }}"
stacksets:
  - name: iam-stackset-execution-policy
  - name: iam-read-only
  - name: iam-jenkins-execution
  - name: iam-cldarch-jenkins-exe-role