--- 
AWSTemplateFormatVersion: "2010-09-09"
Description: Creating sns topic to notify Ops team regarding system cofiguration
Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: "GP.Cloud.Ops@ge.com"
          Protocol: "email"
      TopicName: "GpCloudWatchMetrics"
      KmsMasterKeyId: !Sub "arn:aws:kms:us-east-1:${AWS::AccountId}:alias/common-sns-key"
Outputs:
  SnsARN:
    Description: Arn of the Sns-topic
    Value: !Ref MySNSTopic
    Export:
      Name: "gp-sns-topic-ARN"
