---
account: '{{ aws_account_id }}'
region: "{{ aws_region }}"
terminate: {{ terminate }}
stacksets:
  - name: iam-common-managed-policy-deploy-role
  - name: iam-common-managed-policy-fed-role
  - name: iam-ssm-common-managed-policies
  - name: iam-gesos-ecr-access-policy