- name: Include variable file
  include_vars: stackset-exe-role-vars.yml

- name: Creating stackset exe role cloudformationstack
  cloudformation:
    stack_name: "gp-stackset-execution"
    state: "present"
    region: "{{ aws_region }}"
    template: "{{role_path}}/files/stackset-execution.yml"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ session_token }}"