---
- name: Include vars file
  include_vars: main.yml

- name: Create a new directory <account-name>-<account-id>
  file:
    state: directory
    path: "{{source_directory}}/{{ aws_account_name }}-{{ aws_account_id }}"

- name: Copy 32-dbss-dba-components.yml
  template:
    src: "32-dbss-dba-components.yml"
    dest: "{{source_directory}}/{{ aws_account_name }}-{{ aws_account_id }}"

- name: Copy 34-dbss-dba-parameter-option-groups.yml
  template:
    src: "34-dbss-dba-parameter-option-groups.yml"
    dest: "{{source_directory}}/{{ aws_account_name }}-{{ aws_account_id }}"

- debug: var=ansible_date_time

- name: Copy Ansible Metadata file
  template:
    src: "{{role_path}}/files/ansible_metadata.txt"
    dest: "{{source_directory}}/ansible_metadata.txt"
  vars:
    current_date_jinja: "{{ ansible_date_time.date }} {{ansible_date_time.time}} UTC"

- name: Call Git role
  include_role:
    name: git-push
  vars:
    github_enterprise_repo: gr-accounts-setup
    message: "Ansible rendered stackset files"