---
- set_stats:
    data:
      to_be_deleted:
        - folder_name: vpc-endpoint
          repo: cft-infra-templates
          message: "Ansible is deleting vpc-endpoint"
          stackNames:
            - "{{prefix}}ecr-api-endpoint"
            - "{{prefix}}ecr-dkr-endpoint"
            - "{{prefix}}execute-api-endpoint"
            - "{{prefix}}kinesis-streams-endpoint"
            - "{{prefix}}s3-endpoint"
            - "{{prefix}}secretsmanager-endpoint"
            - "{{prefix}}sqs-endpoint"

- name: New folder for endpoints
  file:
    state: directory
    path: "/tmp/account-automation-folder/endpoints/"

- name: Render CF template
  template:
    src: "{{item}}"
    dest: "/tmp/account-automation-folder/endpoints/"
  loop:
    - ecr-api-endpoint.yml
    - ecr-dkr-endpoint.yml
    - execute-api-endpoint.yml
    - kinesis-streams-endpoint.yml
    - s3-endpoint.yml
    - secretsmanager-endpoint.yml
    - sqs-endpoint.yml

- name: Create endpoints stack
  cloudformation:
    stack_name: "{{prefix}}{{item.stackName}}"
    state: "present"
    region: "{{ aws_region }}"
    template: "/tmp/account-automation-folder/endpoints/{{item.templateName}}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ session_token }}"
  loop:
    - { stackName: "s3-endpoint", templateName: "s3-endpoint.yml"}
    - { stackName: "sqs-endpoint", templateName: "sqs-endpoint.yml"}
    - { stackName: "ecr-dkr-endpoint", templateName: "ecr-dkr-endpoint.yml"}
    - { stackName: "ecr-api-endpoint", templateName: "ecr-api-endpoint.yml"}
    - { stackName: "execute-api-endpoint", templateName: "execute-api-endpoint.yml"}
    - { stackName: "kinesis-streams-endpoint", templateName: "kinesis-streams-endpoint.yml"}
    - { stackName: "secretsmanager-endpoint", templateName: "secretsmanager-endpoint.yml"}

- name: Render CFT files
  include_tasks: endpoints-render.yml

- name: Call Git role
  include_role:
    name: git-push
  vars:
    github_enterprise_org: "{{org}}"
    github_enterprise_repo: cft-infra-templates
    message: "Ansible is creating vpc-endpoint"