AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  AppName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9-]*$
    Description: Input the Application Name. Accepts only lowercase, uppercase, number and hyphen
  Env:
    Type: String
    Default: prd
    AllowedValues:
      - 'nonprd'
      - 'prd'
    Description: Choose relevant Environment.
  UAI:
    Type: String
    Description: The UAI of the application being managed. UAI starting sequence MUST be in uppercase.
    ConstraintDescription: The UAI must be valid, but specified as 'UAI' in upper case followed by 7 digits
    AllowedPattern: '^uai[0-9]*$'
    MinLength: 10
    MaxLength: 10
    Default: uai3037033

Resources:
  GSCDatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${UAI}-${AppName}-${Env}-ansibleapikey'
      KmsKeyId: !ImportValue ldapcommonkmskeyname
      Description: This secret has a hardcoded password in SecretString (use GenerateSecretString instead)
      SecretString: '{"Ansibleoauth2Tokenvalue":"Value"}'
      Tags:
        - Key: Name
          Value: !Sub '${UAI}-${AppName}-${Env}-ansibleapikey'
        - Key: role
          Value: 'AnsibleAPIKey'
        - Key: uai
          Value: !Ref 'UAI'
        - Key: env
          Value: !Ref 'Env'