AWSTemplateFormatVersion: 2010-09-09
Description: SandBox all SG Groups
Parameters:
  AppName:
    Type: String
    Default: ldap
  UAI:
    Type: String
    Default: uai3037033
  Env:
    Type: String
    Default: prd

Resources:
  ServiceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'SG for Lambda Function ${UAI}-${AppName}-${Env}-Service'
      GroupName: !Sub "${UAI}-${AppName}-${Env}-Service"
      VpcId: !ImportValue vpcid
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5001
          ToPort: 5001
          SourceSecurityGroupId: !ImportValue ldapLoadBalancerSg
          Description: 'This is setup to allow connection from ALB to Service'
        - IpProtocol: tcp
          FromPort: 8005
          ToPort: 8005
          SourceSecurityGroupId: !ImportValue ldapLoadBalancerSg
          Description: 'This is setup to allow connection from ALB to Service'
      Tags:
        - Key: Name
          Value: !Sub "${UAI}-${AppName}-${Env}-Service"
        - Key: uai
          Value: !Ref UAI
        - Key: Env
          Value: !Ref Env

Outputs:
  ServiceSG:
    Description: "SG of the Service"
    Value:
      'Fn::GetAtt':
        - ServiceSG
        - GroupId
    Export:
      Name: ldapecsServiceSg