---
account: '{{ aws_account_id }}'
region: "{{ aws_region }}"
terminate: {{ terminate }}
stacksets:
  - name: uai3027632-power-security-automation-fedrole
  - name: uai3027632-power-security-automation-ssm-lambda-svc-role