AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to create required roles for DMS 
## History:
   #This template must be deployed into EACH account that needs to be accessed via these cross-account roles
   # 15-Jul-2021 - SB - Initial commit

Resources:
  dmsvpcrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "dms-vpc-role"         
      Tags:
        - Key: support-group
          Value: dig-tech-cts-cloud-db-support-team
        - Key: uai
          Value: uai3036792

      # The trust policy that is associated with this role.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            "Service": "dms.amazonaws.com"
          Action:
          - sts:AssumeRole
          

      #For attaching Managed policies
      ManagedPolicyArns:        
        - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole

  dmscwrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "dms-cloudwatch-logs-role"         
      Tags:
        - Key: support-group
          Value: dig-tech-cts-cloud-db-support-team
        - Key: uai
          Value: uai3036792

      # The trust policy that is associated with this role.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            "Service": "dms.amazonaws.com"
          Action:
          - sts:AssumeRole
          

      #For attaching Managed policies
      ManagedPolicyArns:        
        - arn:aws:iam::aws:policy/service-role/AmazonDMSCloudWatchLogsRole

  dmsaccessendpoint:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "dms-access-for-endpoint"         
      Tags:
        - Key: support-group
          Value: dig-tech-cts-cloud-db-support-team
        - Key: uai
          Value: uai3036792

      # The trust policy that is associated with this role.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            "Service": "dms.amazonaws.com"
          Action:
          - sts:AssumeRole
        - Effect: Allow
          Principal: 
            "Service": "redshift.amazonaws.com"
          Action:
          - sts:AssumeRole
          

      #For attaching Managed policies
      ManagedPolicyArns:        
        - arn:aws:iam::aws:policy/service-role/AmazonDMSRedshiftS3Role