---
AWSTemplateFormatVersion: '2010-09-09'
Description: Denys get secret for all deploy roles.
Resources:
  CustomManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: deny-get-secret
      Description: Common managed policy for all deploy roles.
      Path: "/"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
	  - Sid: denyGetSecretValue
  	    Effect: Deny
            Action:
   	      - secretsmanager:GetSecretValue
  	    Resource:
              - '*'
  	  
