--- 
AWSTemplateFormatVersion: "2010-09-09"
Description: Creating sns topic to notify Ops team regarding system cofiguration
Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: "GP.Cloud.Ops@ge.com"
          Protocol: "email"
      TopicName: "OpsCloudWatch"
      KmsMasterKeyId: !Sub "arn:aws:kms:us-east-1:${AWS::AccountId}:alias/common-sns-key"
  SnsTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Sid: DefaultPolicy
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'SNS:GetTopicAttributes'
              - 'SNS:SetTopicAttributes'
              - 'SNS:AddPermission'
              - 'SNS:RemovePermission'
              - 'SNS:DeleteTopic'
              - 'SNS:Subscribe'
              - 'SNS:ListSubscriptionsByTopic'
              - 'SNS:Publish'
              - 'SNS:Receive'
            Resource:
              Ref: MySNSTopic
            Condition:
              StringEquals:
                'AWS:SourceOwner':
                  Ref: 'AWS::AccountId'
          - Sid: TrustCWEToPublishEventsToMyTopic
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource:
              Ref: MySNSTopic
      Topics:
        - Ref: MySNSTopic
Outputs:
  SnsARN:
    Description: Arn of the Sns-topic
    Value: !Ref MySNSTopic
    Export:
      Name: "ops-notify-sns-topic"
